MvcProjectCamp/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        

        public ActionResult Index()
        {
            var categoryValues = categoryManager.GetAll();
            return View(categoryValues);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(category);
            if (results.IsValid)
            {
                categoryManager.Add(category);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = categoryManager.GetById(id);
            categoryManager.CategoryDelete(categoryValue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryValue = categoryManager.GetById(id);
            return View(categoryValue);          
        }
        
        [HttpPost]
        public ActionResult EditCategory(Category category)
        {
            categoryManager.CategoryUpdate(category);
            return RedirectToAction("Index");
        }
    }
}

MvcProjectCamp/Views/AdminCategory/AddCategory.cshtml
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@model EntıtyLayer.Concrete.Category

@{
    Layout = null;
}

<h1>Yeni Kategori Ekleme Sayfasi</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adi")
        @Html.TextBoxFor(x => x.CategoryName, new {@class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /> <br />
        @Html.Label("Aciklamayi Yaziniz")
        @Html.TextAreaFor(x => x.CategoryDescription)
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /> <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}



@*<form class="form-group" method="post">
        <input type="text" placeholder="Kategori Adi" name="CategoryName" class="form-control" />
        <br />
        <input type="text" placeholder="Aciklama Giriniz" name="CategoryDescription" class="form-control" />
        <br />
        <button class="btn btn-info">Ekle</button>
    </form>*@

MvcProjectCamp/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<h2>Kategori Guncelleme Sayfasi</h2>
@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori ID")
    @Html.TextBoxFor(x => x.CategoryId, new {@class = "form-control" })
    <br />
    @Html.Label("Kategori Adi")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    @Html.Label("Kategori Aciklama")
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br />  
    <button class="btn btn-success">Guncelle</button> 

</div>
}

MvcProjectCamp/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>


@{
    Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori Adi</th>
        <th>Sil</th>
        <th>Guncelle</th>
        <th>Basliklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/EditCategory/@item.CategoryId" class="btn btn-warning">Guncelle</a></td>
            <td><a href="#" class="btn btn-primary">Basliklar</a></td>
        </tr>
    }
</table>

<br />
<a href="/AdminCategory/AddCategory" class="btn btn-dark">Yeni Kategori</a>