MvcProjectCamp/Controllers/HeadingController.cs
using BusinessLayer.Abstract;
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Metadata.Edm;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjectCamp.Controllers
{
    public class HeadingController : Controller
    {
        HeadingManager headingManager = new HeadingManager(new EfHeadingDal());
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        WriterManager writerManager = new WriterManager(new EfWriterDal());
        // GET: Heading
        public ActionResult Index()
        {
            var headingValues = headingManager.GetAll();
            return View(headingValues);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valueCategory = (from x in categoryManager.GetAll()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryId.ToString()
                                                  }).ToList();

            List<SelectListItem> valueWriter = (from x in writerManager.GetAll()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.WriterId.ToString()
                                                }).ToList();
            ViewBag.vlc = valueCategory;
            ViewBag.vlw = valueWriter;
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading heading)
        {
            heading.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            headingManager.AddHeading(heading);
            return RedirectToAction("Index");
        }

       
    }
}

MvcProjectCamp/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Baslik Ekleme Sayfasi</h1>
<br />
@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Baslik Adi")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.HeadingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.CategoryId, (List<SelectListItem>)ViewBag.vlc, new {@class = "form-control"})
        <br />
        @Html.Label("Yazar")
        @Html.DropDownListFor(x => x.WriterId, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
        <br />
        <button class="btn btn-info">Basligi Olustur</button>
    </div>
}

MvcProjectCamp/Views/Heading/ContentByHeading.cshtml
@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            <div class="time-label">
                                <span class="bg-success">Tarih</span>
                            </div>
                            <!-- /.timeline-label -->
                            <!-- timeline item -->
                            <div>
                                <i class="fas fa-comment bg-yellow"></i>
                                <div class="timeline-item">
                                    <h3 class="timeline-header"><a href="#">Test</a> Deneme</h3>
                                    <div class="timeline-body">
                                        İçerik
                                    </div>
                                </div>
                            </div>
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProjectCamp/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{ string color = "";}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">

                </div>
            </div>
        </div>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 30%">
                                Yazarı
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Tiyatro")
                            {
                                color = "badge badge-warning";
                            }
                            if (item.Category.CategoryName == "Teknoloji")
                            {
                                color = "badge badge-primary";
                            }
                            if (item.Category.CategoryName == "Kitap")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.CategoryName == "Seyahat")
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-secondary";
                            }
                            <tr>
                                <td>
                                    @item.HeadingId
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>

                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        İçerik
                                    </a>
                                    <a class="btn btn-info btn-sm" href="#">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="#">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </section>
</body>
</html>

<br />
<a href="/Heading/AddHeading/" class="btn btn-info">Yeni Baslik Girisi</a>

@*<br/>
    <h2>Index</h2>
    <table class="table table-bordered">
        <tr>
            <th>Id</th>
            <th>Baslik</th>
            <th>Kategori</th>
        </tr>
        @foreach(var item in Model)
                {
                    <tr>
                        <td>@item.HeadingId</td>
                        <td>@item.HeadingName</td>
                        <td>@item.Category.CategoryName</td>
                    </tr>
                }
    </table>*@